# Generated by Django 4.1.7 on 2023-02-24 07:23

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0003_rename__end_date_lactation_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='date_of_birth',
            field=models.DateField(error_messages={'max_value': 'The date of birth cannot be in the future!.'}, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 2, 24))]),
        ),
        migrations.AlterField(
            model_name='cow',
            name='date_of_death',
            field=models.DateField(blank=True, error_messages={'max_value': 'The date of death cannot be in the future!.'}, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 2, 24))]),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='pregnancy_failed_date',
            field=models.DateField(blank=True, error_messages={'max_value': 'Future records not allowed!.'}, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 2, 24))]),
        ),
    ]
