# Generated by Django 4.2.2 on 2023-06-07 04:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='date_of_birth',
            field=models.DateField(error_messages={'max_value': 'The date of birth cannot be in the future!.'}, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 6, 7))]),
        ),
        migrations.AlterField(
            model_name='cow',
            name='date_of_death',
            field=models.DateField(blank=True, error_messages={'max_value': 'The date of death cannot be in the future!.'}, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 6, 7))]),
        ),
        migrations.AlterField(
            model_name='insemination',
            name='date_of_insemination',
            field=models.DateField(error_messages={'max_value': 'Invalid date entry, Dates must not be in future'}, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 6, 7))]),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='pregnancy_failed_date',
            field=models.DateField(blank=True, error_messages={'max_value': 'Future records not allowed!.'}, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 6, 7))]),
        ),
        migrations.AlterField(
            model_name='semen',
            name='date_of_expiry',
            field=models.DateField(error_messages={'min_value': 'Invalid date entry, Date of expiry must be in future'}, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 6, 7))]),
        ),
        migrations.AlterField(
            model_name='semen',
            name='date_of_production',
            field=models.DateField(error_messages={'max_value': 'Invalid date entry, Dates of production must not be in future'}, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 6, 7))]),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='date_observed',
            field=models.DateField(error_messages={'max_value': 'The date of observation cannot be in the future!.'}, validators=[django.core.validators.MaxValueValidator(datetime.date(2023, 6, 7))]),
        ),
    ]
